### ISSUE TITLE
Error On Creating New Addon From Template

### ISSUE THREAD

**Issue by pr0crustes** [Jochnickel/addon_template_butt#2]
Using the "Create New Addon From Existing Addon" (selecting the template) will cause an error. This template includes invalid paths.

Log [also available as git](https://gist.github.com/pr0crustes/53b16434047bb9343dd07648727acadc):
`
[ResourceCopy] Wrote non-resource file : 'D:\Steam\steamapps\common\dota 2 beta\game\dota_addons\dota2_but_this_will_not_copy\addoninfo.txt'
[ResourceCopy] Wrote resource file: 'D:\Steam\steamapps\common\dota 2 beta\game\dota_addons\dota2_but_this_will_not_copy\panorama\layout\custom_game\current_options.vxml_c'
[ResourceCopy] Wrote resource file: 'D:\Steam\steamapps\common\dota 2 beta\game\dota_addons\dota2_but_this_will_not_copy\panorama\layout\custom_game\custom_ui_manifest.vxml_c'
[ResourceCopy] Wrote resource file: 'D:\Steam\steamapps\common\dota 2 beta\game\dota_addons\dota2_but_this_will_not_copy\panorama\layout\custom_game\game_info.vxml_c'
[ResourceCopy] Wrote resource file: 'D:\Steam\steamapps\common\dota 2 beta\game\dota_addons\dota2_but_this_will_not_copy\panorama\layout\custom_game\multiteam_end_screen.vxml_c'
[ResourceCopy] Wrote resource file: 'D:\Steam\steamapps\common\dota 2 beta\game\dota_addons\dota2_but_this_will_not_copy\panorama\layout\custom_game\multiteam_end_screen_player.vxml_c'
[ResourceCopy] Wrote resource file: 'D:\Steam\steamapps\common\dota 2 beta\game\dota_addons\dota2_but_this_will_not_copy\panorama\layout\custom_game\team_select_butt.vxml_c'
[ResourceCopy] Wrote resource file: 'D:\Steam\steamapps\common\dota 2 beta\game\dota_addons\dota2_but_this_will_not_copy\panorama\scripts\custom_game\multiteam_end_screen_butt.vjs_c'
[ResourceCopy] Wrote resource file: 'D:\Steam\steamapps\common\dota 2 beta\game\dota_addons\dota2_but_this_will_not_copy\panorama\scripts\custom_game\team_select_butt.vjs_c'
[ResourceCopy] Wrote resource file: 'D:\Steam\steamapps\common\dota 2 beta\game\dota_addons\dota2_but_this_will_not_copy\panorama\styles\custom_game\current_options.vcss_c'
[ResourceCopy] Wrote resource file: 'D:\Steam\steamapps\common\dota 2 beta\game\dota_addons\dota2_but_this_will_not_copy\panorama\styles\custom_game\team_select_butt.vcss_c'
[ResourceCopy] Wrote non-resource file : 'D:\Steam\steamapps\common\dota 2 beta\game\dota_addons\dota2_but_this_will_not_copy\resource\addon_english.txt'
[ResourceCopy] Wrote non-resource file : 'D:\Steam\steamapps\common\dota 2 beta\game\dota_addons\dota2_but_this_will_not_copy\scripts\custom_net_tables.txt'
[ResourceCopy] Wrote non-resource file : 'D:\Steam\steamapps\common\dota 2 beta\game\dota_addons\dota2_but_this_will_not_copy\scripts\npc\abilities.txt'
[ResourceCopy] Wrote non-resource file : 'D:\Steam\steamapps\common\dota 2 beta\game\dota_addons\dota2_but_this_will_not_copy\scripts\npc\heroes.txt'
[ResourceCopy] Wrote non-resource file : 'D:\Steam\steamapps\common\dota 2 beta\game\dota_addons\dota2_but_this_will_not_copy\scripts\npc\herolist.txt'
[ResourceCopy] Wrote non-resource file : 'D:\Steam\steamapps\common\dota 2 beta\game\dota_addons\dota2_but_this_will_not_copy\scripts\npc\items.txt'
[ResourceCopy] Wrote non-resource file : 'D:\Steam\steamapps\common\dota 2 beta\game\dota_addons\dota2_but_this_will_not_copy\scripts\npc\npc_abilities_custom.txt'
[ResourceCopy] Wrote non-resource file : 'D:\Steam\steamapps\common\dota 2 beta\game\dota_addons\dota2_but_this_will_not_copy\scripts\npc\npc_heroes_custom.txt'
[ResourceCopy] Wrote non-resource file : 'D:\Steam\steamapps\common\dota 2 beta\game\dota_addons\dota2_but_this_will_not_copy\scripts\npc\npc_items_custom.txt'
[ResourceCopy] Wrote non-resource file : 'D:\Steam\steamapps\common\dota 2 beta\game\dota_addons\dota2_but_this_will_not_copy\scripts\npc\npc_items_override.txt'
[ResourceCopy] Wrote non-resource file : 'D:\Steam\steamapps\common\dota 2 beta\game\dota_addons\dota2_but_this_will_not_copy\scripts\npc\npc_units_custom.txt'
[ResourceCopy] Wrote non-resource file : 'D:\Steam\steamapps\common\dota 2 beta\game\dota_addons\dota2_but_this_will_not_copy\scripts\npc\units.txt'
[ResourceCopy] Wrote non-resource file : 'D:\Steam\steamapps\common\dota 2 beta\game\dota_addons\dota2_but_this_will_not_copy\scripts\vscripts\addon_game_mode.lua'
[ResourceCopy] Wrote non-resource file : 'D:\Steam\steamapps\common\dota 2 beta\game\dota_addons\dota2_but_this_will_not_copy\scripts\vscripts\events.lua'
[ResourceCopy] Wrote non-resource file : 'D:\Steam\steamapps\common\dota 2 beta\game\dota_addons\dota2_but_this_will_not_copy\scripts\vscripts\filters.lua'
[ResourceCopy] Wrote non-resource file : 'D:\Steam\steamapps\common\dota 2 beta\game\dota_addons\dota2_but_this_will_not_copy\scripts\vscripts\settings_butt.lua'
[ResourceCopy] Wrote non-resource file : 'D:\Steam\steamapps\common\dota 2 beta\game\dota_addons\dota2_but_this_will_not_copy\scripts\vscripts\settings_misc.lua'
[ResourceCopy] Wrote non-resource file : 'D:\Steam\steamapps\common\dota 2 beta\game\dota_addons\dota2_but_this_will_not_copy\scripts\vscripts\startitems.lua'
[ResourceCopy] Wrote non-resource file : 'D:\Steam\steamapps\common\dota 2 beta\game\dota_addons\dota2_but_this_will_not_copy\scripts\vscripts\thinker.lua'
[ResourceCopy] Wrote non-resource file : 'D:\Steam\steamapps\common\dota 2 beta\game\dota_addons\dota2_but_this_will_not_copy\scripts\vscripts\abilities\exampleability.lua'
[ResourceCopyError] WARNING: Invalid destination path 'D:\Steam\steamapps\common\dota 2 beta\game\dota_addons\dota2_but_this_will_not_copy\scripts\vscripts\deprecated files for research\eventtest.lua' (The filename may only contain lower case alphanumeric characters and underscores.)
[ResourceCopyError] WARNING: Invalid destination path 'D:\Steam\steamapps\common\dota 2 beta\game\dota_addons\dota2_but_this_will_not_copy\scripts\vscripts\deprecated files for research\gamemode.lua' (The filename may only contain lower case alphanumeric characters and underscores.)
[ResourceCopyError] WARNING: Invalid destination path 'D:\Steam\steamapps\common\dota 2 beta\game\dota_addons\dota2_but_this_will_not_copy\scripts\vscripts\deprecated files for research\settings.lua' (The filename may only contain lower case alphanumeric characters and underscores.)
[ResourceCopy] Wrote non-resource file : 'D:\Steam\steamapps\common\dota 2 beta\game\dota_addons\dota2_but_this_will_not_copy\scripts\vscripts\internal\events.lua'
[ResourceCopy] Wrote non-resource file : 'D:\Steam\steamapps\common\dota 2 beta\game\dota_addons\dota2_but_this_will_not_copy\scripts\vscripts\internal\panorama.lua'
[ResourceCopy] Wrote non-resource file : 'D:\Steam\steamapps\common\dota 2 beta\game\dota_addons\dota2_but_this_will_not_copy\scripts\vscripts\internal\talents.lua'
[ResourceCopy] Wrote non-resource file : 'D:\Steam\steamapps\common\dota 2 beta\game\dota_addons\dota2_but_this_will_not_copy\scripts\vscripts\internal\thinker.lua'
[ResourceCopyError] WARNING: Invalid destination path 'D:\Steam\steamapps\common\dota 2 beta\game\dota_addons\dota2_but_this_will_not_copy\scripts\vscripts\internal\XPModifier.lua' (The filename may only contain lower case alphanumeric characters and underscores.)
[ResourceCopy] Wrote non-resource file : 'D:\Steam\steamapps\common\dota 2 beta\game\dota_addons\dota2_but_this_will_not_copy\scripts\vscripts\modifiers\examplemodifier.lua'
[ResourceCopy] Wrote non-resource file : 'D:\Steam\steamapps\common\dota 2 beta\game\dota_addons\dota2_but_this_will_not_copy\scripts\vscripts\talents\modifier_special_bonus_base.lua'
[ResourceCopy] Wrote non-resource file : 'D:\Steam\steamapps\common\dota 2 beta\game\dota_addons\dota2_but_this_will_not_copy\scripts\vscripts\talents\modifier_special_bonus_exampletalent.lua'
[ResourceCopyError] WARNING: Invalid destination path 'D:\Steam\steamapps\common\dota 2 beta\game\dota_addons\dota2_but_this_will_not_copy\scripts\vscripts\utils\ButtAPI.lua' (The filename may only contain lower case alphanumeric characters and underscores.)
[ResourceCopy] Wrote non-resource file : 'D:\Steam\steamapps\common\dota 2 beta\game\dota_addons\dota2_but_this_will_not_copy\scripts\vscripts\utils\particles.lua'
[ResourceCopy] Wrote non-resource file : 'D:\Steam\steamapps\common\dota 2 beta\game\dota_addons\dota2_but_this_will_not_copy\scripts\vscripts\utils\shortcuts.lua'
[ResourceCopy] Wrote non-resource file : 'D:\Steam\steamapps\common\dota 2 beta\game\dota_addons\dota2_but_this_will_not_copy\scripts\vscripts\utils\timers.lua'
[ResourceCopy] Wrote non-resource file : 'D:\Steam\steamapps\common\dota 2 beta\game\dota_addons\dota2_but_this_will_not_copy\scripts\vscripts\utils\util.lua'
[ResourceCopy] Wrote resource file: 'D:\Steam\steamapps\common\dota 2 beta\game\dota_addons\dota2_but_this_will_not_copy\soundevents\custom_sounds.vsndevts_c'
[ResourceCopy] Wrote resource file: 'D:\Steam\steamapps\common\dota 2 beta\game\dota_addons\dota2_but_this_will_not_copy\sounds\hitme.vsnd_c'
[ResourceCopyError] Processed 49 files with 5 errors. (0 skipped)
`

**Comment by pr0crustes** [comment]
I just submitted a pull request #3 that fixes this issue.

**Comment by Jochnickel** [comment]
done :)
