### ISSUE TITLE
Skeleton Archer doesn't disappear(Clinkz)

### ISSUE THREAD

**Issue by GniLudio** [Jochnickel/addon_template_butt#20]
**Console output:**
Bad key for entity "npc_dota_clinkz_skeleton_archer": Out of range parsed value for field "teamnumber" (-1)!
EntIndexToHScript parameter 1: expected integer but got void.
scripts\vscripts\filters.lua:40: Parameter type mismatch
stack traceback:
    [C]: in function 'EntIndexToHScript'
    scripts\vscripts\filters.lua:40: in function <scripts\vscripts\filters.lua:38>
Script Runtime Error: scripts\vscripts\filters.lua:40: Parameter type mismatch
stack traceback:
    [C]: in function 'EntIndexToHScript'
    scripts\vscripts\filters.lua:40: in function <scripts\vscripts\filters.lua:38>

**Comment by Jochnickel** [comment]
thanks :)
volvo spaghetti :D
