### ISSUE TITLE
Old armor formula does not work on illusions

### ISSUE THREAD

**Issue by AdmiralMyxtaR** [Jochnickel/addon_template_butt#5]
Illsuions are still using new formula and invulnerable to physical damage after 225 armor. May be unfixable, since MODIFIER_PROPERTY_PHYSICAL_ARMOR_BONUS doesn't work on illusions and MODIFIER_PROPERTY_PHYSICAL_ARMOR_BONUS_ILLUSIONS doesn't seem to do anything

**Comment by Jochnickel** [comment]
Probably the most important difference between main and bonus armor is that illusions only benefit from main armor, although their HUD still shows the bonus armor just like on other heroes, to make them less obvious to the enemy.

**Comment by Jochnickel** [comment]
solved by force damage :D
