### ISSUE TITLE
Can't open map in hammer

### ISSUE THREAD

**Issue by TheWWWorm** [Jochnickel/addon_template_butt#61]
I get this error. I just created an empty addon, and copy pasted the addon_template_butt with replacments, as was mentioned in tutorial. I get errors bellow. 
![image](https://user-images.githubusercontent.com/24833170/83976001-ca287f80-a8ff-11ea-9971-49dd204a20c6.png)
![image](https://user-images.githubusercontent.com/24833170/83976009-ddd3e600-a8ff-11ea-836e-0b08c422655c.png)

Is there something I might be doing incorrectly? Thank you

**Comment by Jochnickel** [comment]
have not been modding in a while. might have been an error with my update bot

**Comment by thomasthe1st** [comment]
Same for me. Can't load dota.vmap with same error. Other files like the template_vmap can be loaded. Also the general dota.vmap can be loaded.

**Comment by TheWWWorm** [comment]
@thomasthe1st use https://github.com/BOTRaiquia/dota2buttemplate_fixed it works fine
