### ISSUE TITLE
Respawn time reduction doesn't work past level 25

### ISSUE THREAD

**Issue by TheGoldenProof** [Jochnickel/addon_template_butt#7]
Like the title says, the respawn time reduction % doesn't affect respawn times for levels greater than 25.

On a similar note, with previous templates, there was the option to add a constant amount to the reduced respawn time (opposed to the either/or here), which I used in most of my modes, but that is missing here.

EDIT: the fixed rate respawn time doesn't work past level 25 either.

**Comment by Jochnickel** [comment]
fix it with a Workaround, like "Nein nein nein. yu yuse 11% cooldown"
