### ISSUE TITLE
Aghanim's Scepter upgrades no longer working

### ISSUE THREAD

**Issue by JrTheDragon01** [Jochnickel/addon_template_butt#8]
As of a recent update to DotA, the provided templates for datadriven heroes, abilities, items etc. do not function with Aghanim's Scepter upgrades, replacing many of the values with zero. Example: Lion's finger of death has zero cooldown, mana cost and deals zero damage when Aghanim's Scepter is equipped.

**Comment by JrTheDragon01** [comment]
It appears that the solution to this problem is adding the tag 

`"RequiresScepter"			"1"`

To each scepter-dependent AbilitySpecial value

**Comment by Jochnickel** [comment]
yea i forget to update sometimes
